language: node_js

addons:
  apt:
    packages:
      - git
      - make
      - curl

node_js:
  - 'node'
  - 'lts/*'

install:
  - make init

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build
  - make terraform/install
  - make terraform/get-plugins
  - make terraform/get-modules
  - make terraform/lint
  - make terraform/validate

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
